org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true

# Maven Central publishing coordinates
GROUP=com.elveum
VERSION_NAME=2.1.0-beta03

# POM metadata
POM_DESCRIPTION=A library for simplifying state management and data loading in Android applications
POM_URL=https://github.com/romychab/container

POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://github.com/romychab/container/blob/main/LICENSE

POM_SCM_URL=https://github.com/romychab/container
POM_SCM_CONNECTION=scm:git:git://github.com/romychab/container.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/romychab/container.git

POM_DEVELOPER_ID=romychab
POM_DEVELOPER_NAME=Roman Andrushchenko
POM_DEVELOPER_URL=https://github.com/romychab
POM_DEVELOPER_EMAIL=rom.andrushchenko@gmail.com
