site_name: Container
site_url: https://docs.uandcode.com/container/
site_description: A library for simplifying state management and data loading in Android applications
site_dir: build/mkdocs
docs_dir: build/mkdocs-src
repo_url: https://github.com/romychab/container
repo_name: GitHub
edit_uri: ""

theme:
  name: material
  features:
    - navigation.top
    - navigation.footer
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Container Type: container-type.md
  - Reducer Pattern: reducer-pattern.md
  - Subjects & Cache: subjects.md
  - Pagination: paging.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences